## PostgreSQL bitnami chart
## ref: https://github.com/bitnami/bitnami-docker-postgresql/

## PostgreSQL user (has superuser privileges if username is `postgres`)
# postgresqlUsername: postgres

## PostgreSQL password
# postgresqlPassword: kong

## Create a database
# postgresqlDatabase: kong

auth:
  postgresPassword: "kong"
  username: "kong"
  password: "kong"
  database: "kong"